version: "3.8"
services:
  database:
    image: postgres:14
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_DB: sample
      POSTGRES_USER: sample
      POSTGRES_PASSWORD: sample
      PGDATA: /var/lib/postgresql/data/sample
  redis:
    image: redis:6-alpine
    ports:
      - "127.0.0.1:6379:6379"
  redis-insight:
    image: redislabs/redisinsight:latest
    ports:
      - "127.0.0.1:8001:8001"
    depends_on:
      - redis
