version: "3.8"
services:
  database:
    image: postgres:13
    ports:
      - "127.0.0.1:5433:5432"
    environment:
      POSTGRES_DB: sample
      POSTGRES_USER: sample
      POSTGRES_PASSWORD: sample
      PGDATA: /var/lib/postgresql/data/sample
  redis:
    image: redis:6-alpine
    ports:
      - "127.0.0.1:6380:6379"
  redis-insight:
    image: redislabs/redisinsight:latest
    ports:
      - "127.0.0.1:8002:8001"
    depends_on:
      - redis
  app:
    image: mbodev/quarkus-sample-distroless:latest
    ports:
      - "127.0.0.1:8081:8080"
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://database:5432/sample
      QUARKUS_REDIS_HOSTS: redis://redis:6379
    depends_on:
      - database
      - redis
    links:
      - database
      - redis
